# Generated by Django 4.2.25 on 2025-10-22 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Track name', max_length=200)),
                ('address', models.TextField(help_text='Full track address')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('description', models.TextField(blank=True, help_text='Track description for public display')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('OPEN_SESSION', 'Open Session'), ('GRAND_PRIX', 'Grand Prix')], default='OPEN_SESSION', help_text='Type of racing session', max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='Session start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Session end date and time')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of drivers allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Session price in euros', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Session description or special notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session_slots.track')),
            ],
            options={
                'verbose_name': 'Session Slot',
                'verbose_name_plural': 'Session Slots',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['track', 'start_datetime'], name='session_slo_track_i_a39337_idx'), models.Index(fields=['start_datetime'], name='session_slo_start_d_baa655_idx')],
            },
        ),
    ]
