# Generated by Django 4.2.25 on 2025-11-03 10:23

from django.db import migrations


def create_role_groups(apps, schema_editor):
    """
    Create Django Groups corresponding to Profile roles.
    This allows role-based permissions to work with Django's built-in system.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Create groups for each role
    drivers_group, _ = Group.objects.get_or_create(name="Drivers")
    managers_group, _ = Group.objects.get_or_create(name="Managers")
    marshals_group, _ = Group.objects.get_or_create(name="Marshals")

    # Get permissions for bookings app
    try:
        view_booking = Permission.objects.get(codename="view_booking", content_type__app_label="bookings")
        add_booking = Permission.objects.get(codename="add_booking", content_type__app_label="bookings")
        change_booking = Permission.objects.get(codename="change_booking", content_type__app_label="bookings")
        delete_booking = Permission.objects.get(codename="delete_booking", content_type__app_label="bookings")

        # Drivers: can view and add their own bookings
        drivers_group.permissions.set([view_booking, add_booking])

        # Managers: full booking permissions
        managers_group.permissions.set([view_booking, add_booking, change_booking, delete_booking])

        # Marshals: can view all bookings and change them (for safety)
        marshals_group.permissions.set([view_booking, change_booking])
    except Permission.DoesNotExist:
        # Permissions don't exist yet (running migrations for first time)
        pass


def remove_role_groups(apps, schema_editor):
    """Remove the role groups if migration is reversed."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Drivers", "Managers", "Marshals"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_role_groups, remove_role_groups),
    ]
