# Generated by Django 4.2.25 on 2025-10-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Unique kart number (1-99)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', help_text='Current operational status of the kart', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about kart condition or maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kart',
                'verbose_name_plural': 'Karts',
                'ordering': ['number'],
            },
        ),
    ]
