# Generated by Django 4.2.25 on 2025-10-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session_slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_kart_number', models.PositiveIntegerField(blank=True, help_text='Driver preferred kart number (optional)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current booking status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_notes', models.TextField(blank=True, help_text='Notes from the driver')),
                ('manager_notes', models.TextField(blank=True, help_text='Internal manager notes')),
                ('assigned_kart', models.ForeignKey(blank=True, help_text='Kart assigned on confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='karts.kart')),
                ('driver', models.ForeignKey(help_text='Driver making the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('session_slot', models.ForeignKey(help_text='The session being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='session_slots.sessionslot')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver'], name='bookings_bo_driver__8cb357_idx'), models.Index(fields=['session_slot'], name='bookings_bo_session_65994c_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
