# Generated by Django 4.2.25 on 2025-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["driver", "session_slot"], name="bookings_bo_driver__78bf21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["session_slot", "status"], name="bookings_bo_session_1b7fb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["driver", "status"], name="bookings_bo_driver__5f78d7_idx"
            ),
        ),
    ]
